# Generated by Django 5.0 on 2023-12-17 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('loan_id', models.CharField(db_column='loan_id', max_length=50, primary_key=True, serialize=False)),
                ('investment_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cash_flows',
            fields=[
                ('cashflow_id', models.CharField(db_column='cashflow_id', max_length=50, primary_key=True, serialize=False)),
                ('cashflow_date', models.DateField()),
                ('cashflow_currency', models.CharField(max_length=15)),
                ('cashflow_type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_id', models.ForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.CASCADE, to='investment.trades')),
            ],
        ),
    ]
